### ISSUE TITLE
Version 0.7.7 crashed on Windows10: need to fix

### ISSUE THREAD

**Issue by SerhiiZavalko** [Arriven/db1000n#339]
**Powershell**
```
PS C:\Users\User\src\war\ddos\db1000n> .\db1000n
2022/03/14 22:16:05.301887 main.go:54: DB1000n [Version: v0.7.7][PID=236]
2022/03/14 22:16:05.301887 countrychecker.go:28: Checking IP address, attempt #0
2022/03/14 22:16:06.750456 countrychecker.go:97: Current country: United Kingdom (2001:ac8:21:f000::212e)
2022/03/14 22:16:06.752756 prometheus.go:213: Can't get system cert pool
2022/03/14 22:16:06.984585 config.go:60: Loading config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.v0.7.json"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0xaf5c23]

goroutine 40 [running]:
crypto/x509.(*CertPool).addCertFunc(...)
        /usr/local/go/src/crypto/x509/cert_pool.go:188
crypto/x509.(*CertPool).AppendCertsFromPEM(0x0, {0xc0000fcc00, 0x3d5, 0x79e19ff64140})
        /usr/local/go/src/crypto/x509/cert_pool.go:226 +0x263
github.com/Arriven/db1000n/src/utils/metrics.getTLSConfig()
        /github/workspace/src/utils/metrics/prometheus.go:227 +0x8a
github.com/Arriven/db1000n/src/utils/metrics.pushMetrics({0x12c8920, 0xc000067a80}, {0xc0000a5680, 0x3, 0xc000068900})
        /github/workspace/src/utils/metrics/prometheus.go:244 +0xeb
created by github.com/Arriven/db1000n/src/utils/metrics.ExportPrometheusMetrics
        /github/workspace/src/utils/metrics/prometheus.go:173 +0x225
```

**CMD**
```
C:\Users\User\src\war\ddos\db1000n>db1000n
2022/03/14 22:17:13.119499 main.go:54: DB1000n [Version: v0.7.7][PID=16144]
2022/03/14 22:17:13.120050 countrychecker.go:28: Checking IP address, attempt #0
2022/03/14 22:17:14.523883 countrychecker.go:97: Current country: United Kingdom (2001:ac8:21:f000::212e)
2022/03/14 22:17:14.527257 prometheus.go:213: Can't get system cert pool
2022/03/14 22:17:14.776472 config.go:60: Loading config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.v0.7.json"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0xaf5c23]

goroutine 67 [running]:
crypto/x509.(*CertPool).addCertFunc(...)
        /usr/local/go/src/crypto/x509/cert_pool.go:188
crypto/x509.(*CertPool).AppendCertsFromPEM(0x0, {0xc000361000, 0x3d5, 0x79f167a311c8})
        /usr/local/go/src/crypto/x509/cert_pool.go:226 +0x263
github.com/Arriven/db1000n/src/utils/metrics.getTLSConfig()
        /github/workspace/src/utils/metrics/prometheus.go:227 +0x8a
github.com/Arriven/db1000n/src/utils/metrics.pushMetrics({0x12c8920, 0xc0004b8000}, {0xc00009d710, 0x3, 0x0})
        /github/workspace/src/utils/metrics/prometheus.go:244 +0xeb
created by github.com/Arriven/db1000n/src/utils/metrics.ExportPrometheusMetrics
        /github/workspace/src/utils/metrics/prometheus.go:173 +0x225
```

**Comment by 5har0varik** [comment]
Same issue

**Comment by kt368** [comment]
Same issue

C:\Users\kt368\Downloads\war\ddos\db1000n>db1000n.exe
2022/03/14 23:46:06.697718 main.go:54: DB1000n [Version: v0.7.7][PID=152360]
2022/03/14 23:46:06.697718 countrychecker.go:28: Checking IP address, attempt #0
2022/03/14 23:46:07.963205 countrychecker.go:97: Current country: Canada (23.16.71.87)
2022/03/14 23:46:07.963205 prometheus.go:213: Can't get system cert pool
2022/03/14 23:46:07.986679 config.go:60: Loading config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.v0.7.json"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x1f5c23]

goroutine 27 [running]:
crypto/x509.(*CertPool).addCertFunc(...)
        /usr/local/go/src/crypto/x509/cert_pool.go:188
crypto/x509.(*CertPool).AppendCertsFromPEM(0x0, {0xc00044cc00, 0x3d5, 0x41f120185d8c})
        /usr/local/go/src/crypto/x509/cert_pool.go:226 +0x263
github.com/Arriven/db1000n/src/utils/metrics.getTLSConfig()
        /github/workspace/src/utils/metrics/prometheus.go:227 +0x8a
github.com/Arriven/db1000n/src/utils/metrics.pushMetrics({0x9c8920, 0xc0004b6000}, {0xc0002138f0, 0x3, 0xc000040540})
        /github/workspace/src/utils/metrics/prometheus.go:244 +0xeb
created by github.com/Arriven/db1000n/src/utils/metrics.ExportPrometheusMetrics
        /github/workspace/src/utils/metrics/prometheus.go:173 +0x225

C:\Users\kt368\Downloads\war\ddos\db1000n>

**Comment by sivillakonski** [comment]
Hi there, chaps!

Thanks for reporting the issue. This is the fix to overcome this problem on Windows machines. Not so skilled to work with the Prometheus, but it should help I believe

**Comment by kt368** [comment]
Could you please explain how to get a working executable file for windows 10 64-bit? My skills in programming is very low...

**Comment by zx6150** [comment]
Probably the same. At startup this shows up and then app crashes

```
2022/03/15 06:24:05.437944 main.go:54: DB1000n [Version: v0.7.7][PID=8456]
2022/03/15 06:24:05.437944 countrychecker.go:28: Checking IP address, attempt #0
2022/03/15 06:24:06.859755 countrychecker.go:97: Current country: Serbia (_MY.VPN.IP.ADRESS_)
2022/03/15 06:24:06.860662 prometheus.go:213: Can't get system cert pool
2022/03/15 06:24:07.053835 config.go:60: Loading config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.v0.7.json"
```

**Comment by bitshape** [comment]
You might want to wait until https://github.com/Arriven/db1000n/pull/342/files is merged as it seems to address this problem

**Comment by Arriven** [comment]
should be fixed in v0.7.8
