### ISSUE TITLE
Panic 

### ISSUE THREAD

**Issue by izac1** [Arriven/db1000n#72]
```2022/03/03 21:59:31 178.248.236.218 is already an IP address, skipping DNS resolution
2022/03/03 21:59:31 178.248.236.218 is already an IP address, skipping DNS resolution
^M^M^M⠋ Flood is in progress, target=178.248.236.218:80, floodType=random, payloadLength=1000 (348 kB, 3.397 MB/s) ^M^M^M⠙ Flood is in progress, target=178.248.236.218:77, floodType=random, payloadLength=100$

runtime stack:
runtime.throw({0x83a6ba, 0x15})
        /usr/local/go/src/runtime/panic.go:1198 +0x71
runtime.(*mheap).sysAlloc(0xc03e20, 0x42b0e0)
        /usr/local/go/src/runtime/malloc.go:756 +0x2d8
runtime.(*mheap).grow(0xc03e20, 0x102)
        /usr/local/go/src/runtime/mheap.go:1347 +0x73
runtime.(*mheap).allocSpan(0xc03e20, 0x102, 0x0, 0x1)
        /usr/local/go/src/runtime/mheap.go:1179 +0x165
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:913 +0x69
runtime.systemstack()
        /usr/local/go/src/runtime/asm_amd64.s:383 +0x49

goroutine 74 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:350 fp=0xc0137ab540 sp=0xc0137ab538 pc=0x4622c0
runtime.(*mheap).alloc(0xc013395960, 0x10, 0x98, 0x0)
        /usr/local/go/src/runtime/mheap.go:907 +0x73 fp=0xc0137ab590 sp=0xc0137ab540 pc=0x427413
runtime.(*mcache).allocLarge(0xc0001acd00, 0x204000, 0xf8, 0x1)
        /usr/local/go/src/runtime/mcache.go:227 +0x89 fp=0xc0137ab5f0 sp=0xc0137ab590 pc=0x418089
runtime.mallocgc(0x204000, 0x0, 0x0)
        /usr/local/go/src/runtime/malloc.go:1088 +0x5c5 fp=0xc0137ab670 sp=0xc0137ab5f0 pc=0x40e605
runtime.growslice(0x11, {0xc00002c948, 0x12, 0xc0133959d0}, 0x10)
        /usr/local/go/src/runtime/slice.go:261 +0x4ac fp=0xc0137ab6d8 sp=0xc0137ab670 pc=0x44b8ec
strings.(*Builder).Write(0xc0000624a0, {0xc02b37e000, 0x203d63, 0x204000})
        /usr/local/go/src/strings/builder.go:90 +0x85 fp=0xc0137ab728 sp=0xc0137ab6d8 pc=0x4e88c5
fmt.Fprint({0x8dad20, 0xc0000624a0}, {0xc0001f97e8, 0x1, 0x1})
        /usr/local/go/src/fmt/print.go:233 +0x75 fp=0xc0137ab778 sp=0xc0137ab728 pc=0x4dd275
text/template.(*state).printValue(0xc0001f99f8, {0x8e8090, 0xc00017b3e0}, {0x78c800, 0xc014fe82b0, 0xffffffffffffffff})
        /usr/local/go/src/text/template/exec.go:964 +0x176 fp=0xc0137ab828 sp=0xc0137ab778 pc=0x615f16
text/template.(*state).walk(0xc0001f99f8, {0x0, 0x0, 0x10000c000166480}, {0x8e8090, 0xc00017b3e0})
        /usr/local/go/src/text/template/exec.go:256 +0x22d fp=0xc0137ab8c8 sp=0xc0137ab828 pc=0x60f4cd
text/template.(*state).walk(0xc0137ab9f8, {0x0, 0x0, 0x0}, {0x8e8360, 0xc00017b2f0})
        /usr/local/go/src/text/template/exec.go:263 +0x37d fp=0xc0137ab968 sp=0xc0137ab8c8 pc=0x60f61d
text/template.(*Template).execute(0xc00053c900, {0x8dad20, 0xc0000624a0}, {0x0, 0x0})
        /usr/local/go/src/text/template/exec.go:217 +0x2d8 fp=0xc0137aba58 sp=0xc0137ab968 pc=0x60f198
text/template.(*Template).Execute(...)
        /usr/local/go/src/text/template/exec.go:200
html/template.(*Template).Execute(0xc00017b200, {0x8dad20, 0xc0000624a0}, {0x0, 0x0})
        /usr/local/go/src/html/template/template.go:124 +0x65 fp=0xc0137aba90 sp=0xc0137aba58 pc=0x6298c5
main.parseStringTemplate({0xc000265c50, 0x27})
        /github/workspace/main.go:170 +0x6c5 fp=0xc0137abc50 sp=0xc0137aba90 pc=0x758265
main.parseByteTemplate(...)```

**Comment by Arriven** [comment]
The stack looks like crash due to OOM - it lacks RAM to parse the config and attack all the targets it's configured to. Check #54 for possible workarounds and more info
